export enum Storage {
  UNION = "UNION",
  SEARCH_TYPE = "SEARCH_TYPE",
  LAST_PARENT_ID = "LAST_PARENT_ID",
  CASE_SENSITIVE = "CASE_SENSITIVE"
}

export enum Message {
  ICON_CLICK = "ICON_CLICK",
  SHORTCUT_COMMAND = "SHORTCUT_COMMAND",
  GET_BOOKMARK_TREE = "GET_BOOKMARK_TREE",
  CREATE_BOOKMARK = "CREATE_BOOKMARK",
  UPDATE_BOOKMARK = "UPDATE_BOOKMARK",
  MOVE_BOOKMARK = "MOVE_BOOKMARK",
  REMOVE_BOOKMARK = "REMOVE_BOOKMARK",
  REMOVE_BOOKMARK_TREE = "REMOVE_BOOKMARK_TREE"
}
